create PROFILE eagles limit
				FAILED_LOGIN_ATTEMPTS 10
				PASSWORD_GRACE_TIME UNLIMITED
				PASSWORD_LIFE_TIME UNLIMITED
				PASSWORD_LOCK_TIME UNLIMITED
				PASSWORD_REUSE_MAX UNLIMITED
				PASSWORD_REUSE_TIME UNLIMITED
				PASSWORD_VERIFY_FUNCTION NULL
				;